#!/bin/bash

PROFILE=profile
REPOS=repos
PROFILE_DIR=$HOME/$PROFILE
REPOS_DIR=$PROFILE_DIR/$REPOS
PACKAGE_LIST_FILE=$PROFILE_DIR/installed_packages
REMOVE_PACKAGE_LIST_FILE=$PROFILE_DIR/remove_packages
YUM_REPO_PATH=/etc/yum.repos.d
